---

- name: Async and wait for module
  hosts: '{{ hosts }}'
  become: true
  tasks:
          - name: Reboot the server {{ inventory_hostname }}
            shell: sleep 5 && shutdown -r now
            async: 1
            poll: 0

          - name: wait for server start
            wait_for:
                    host: "{{ inventory_hostname }}"
                    delay: 30
                    state: started
                    port: 22
            delegate_to: localhost
